apiVersion: ingestron.io/v1alpha1
kind: GeneratorConfig
metadata:
  id: adf
  name: Azure Data Factory Git source
implementation: adf
version: 1.1.0
products:
  - customer-orders
contracts:
  - orders
  - customers
target:
  factoryResourceId: "{{ env.targets.adf.factoryResourceId }}"
schedule:
  enabled: true
  activation: manual
  frequency: Day
  interval: 1
  timeZone: UTC
