apiVersion: ingestron.io/v1alpha1
kind: GeneratorConfig
metadata:
  id: databricks
  name: Databricks Asset Bundle source
implementation: databricks
version: 1.0.0
standards:
  - platform
products:
  - customer-orders
contracts:
  - orders
  - customers
target:
  workspaceHost: "{{ env.targets.databricks.workspaceHost }}"
  rootPath: "{{ env.targets.databricks.rootPath }}"
handoff:
  bronzeRootPath: "{{ env.targets.databricks.bronzeRootPath }}"
