apiVersion: ingestron.io/v1alpha1
kind: GeneratorConfig
metadata:
  id: fabric
  name: Fabric development source
implementation: fabric
version: 1.0.0
products:
  - customer-orders
contracts:
  - orders
  - customers
target:
  workspaceId: "{{ env.targets.fabric.workspaceId }}"
