apiVersion: ingestron.io/v1alpha1
kind: GeneratorConfig
metadata:
  id: synapse
  name: Synapse pipeline Git source
implementation: adf
version: 1.0.0
products:
  - customer-orders
contracts:
  - orders
  - customers
target:
  workspaceName: "{{ env.targets.synapse.workspaceName }}"
